// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo;

public interface testPrx extends Ice.ObjectPrx
{
    public String execute(String mth, String cmd);

    public String execute(String mth, String cmd, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_execute(String mth, String cmd);

    public Ice.AsyncResult begin_execute(String mth, String cmd, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_execute(String mth, String cmd, Ice.Callback __cb);

    public Ice.AsyncResult begin_execute(String mth, String cmd, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_execute(String mth, String cmd, Callback_test_execute __cb);

    public Ice.AsyncResult begin_execute(String mth, String cmd, java.util.Map<String, String> __ctx, Callback_test_execute __cb);

    public Ice.AsyncResult begin_execute(String mth, 
                                         String cmd, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_execute(String mth, 
                                         String cmd, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_execute(String mth, 
                                         String cmd, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_execute(String mth, 
                                         String cmd, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public String end_execute(Ice.AsyncResult __result);
}
